CREATE TABLE IF NOT EXISTS MODELES (
    ID_MODELE INTEGER PRIMARY KEY AUTOINCREMENT,
    NOM_MODELE VARCHAR(255) NOT NULL,
    MARQUE VARCHAR(255),
    COULEUR VARCHAR(100),
    PRIX_UNITAIRE DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS ARTICLES_SKU ( 
    CODE_BARRE VARCHAR(50) PRIMARY KEY,
    ID_MODELE INTEGER,
    TAILLE VARCHAR(50),
    STOCK_PHYSIQUE INT DEFAULT 0,
    STOCK_RESERVE INT DEFAULT 0,
    FOREIGN KEY (ID_MODELE) REFERENCES MODELES(ID_MODELE)
);

CREATE TABLE IF NOT EXISTS EMPLACEMENTS (
    REF_EMPLACEMENT VARCHAR(50) PRIMARY KEY,
    CAPACITE_MAX INT NOT NULL CHECK (CAPACITE_MAX >0),
    ARTICLES_PRESENTS INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS STOCK_EMPLACEMENTS (
    ID_STOCK INTEGER PRIMARY KEY AUTOINCREMENT,
    CODE_BARRE VARCHAR(50),
    REF_EMPLACEMENT VARCHAR(50),
    QUANTITE INT CHECK (QUANTITE >= 0),
    FOREIGN KEY (CODE_BARRE) REFERENCES ARTICLES_SKU(CODE_BARRE),
    FOREIGN KEY (REF_EMPLACEMENT) REFERENCES EMPLACEMENTS(REF_EMPLACEMENT)
);

CREATE TABLE IF NOT EXISTS UTILISATEURS (
    ID_EMPLOYÉ INTEGER PRIMARY KEY AUTOINCREMENT,
    IDENTIFIANT VARCHAR(255) NOT NULL UNIQUE,
    MOT_DE_PASSE VARCHAR(255) NOT NULL,
    NOM_COMPLET VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMMANDES_CLIENTS (
    ID_COMMANDE INTEGER PRIMARY KEY AUTOINCREMENT,
    REF_COMMANDE VARCHAR(100) NOT NULL UNIQUE,
    ADRESSE_LIVRAISON VARCHAR(255) NOT NULL,
    STATUT VARCHAR(50) NOT NULL,
    DATE_CREATION DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_GESTIONNAIRE INTEGER,
    ID_PICKER INTEGER,
    ID_EXPEDITEUR INTEGER,
    FOREIGN KEY (ID_GESTIONNAIRE) REFERENCES UTILISATEURS(ID_EMPLOYÉ),
    FOREIGN KEY (ID_PICKER) REFERENCES UTILISATEURS(ID_EMPLOYÉ),
    FOREIGN KEY (ID_EXPEDITEUR) REFERENCES UTILISATEURS(ID_EMPLOYÉ)
);

CREATE TABLE IF NOT EXISTS LIGNES_COMMANDE (
    ID_LIGNE INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_COMMANDE INTEGER NOT NULL,
    CODE_BARRE VARCHAR(50) NOT NULL,
    QUANTITE_DEMANDEE INT NOT NULL CHECK (QUANTITE_DEMANDEE > 0),
    QUANTITE_PRELEVEE INT DEFAULT 0 CHECK (QUANTITE_PRELEVEE >= 0),
    STATUT_LIGNE VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_COMMANDE) REFERENCES COMMANDES_CLIENTS(ID_COMMANDE),
    FOREIGN KEY (CODE_BARRE) REFERENCES ARTICLES_SKU(CODE_BARRE)
);

CREATE TABLE IF NOT EXISTS HISTORIQUE_MOUVEMENTS (
    ID_MOUVEMENT INTEGER PRIMARY KEY AUTOINCREMENT,
    DATE_MOUV DATETIME DEFAULT CURRENT_TIMESTAMP,
    TYPE_MOUV VARCHAR(50) NOT NULL,
    CODE_BARRE VARCHAR(50) NOT NULL,
    QUANTITE INT NOT NULL,
    REF_EMPLACEMENT_SOURCE VARCHAR(50),
    REF_EMPLACEMENT_CIBLE VARCHAR(50),
    ID_EMPLOYÉ INTEGER,
    FOREIGN KEY (CODE_BARRE) REFERENCES ARTICLES_SKU(CODE_BARRE),
    FOREIGN KEY (ID_EMPLOYÉ) REFERENCES UTILISATEURS(ID_EMPLOYÉ),
    FOREIGN KEY (REF_EMPLACEMENT_SOURCE) REFERENCES EMPLACEMENTS(REF_EMPLACEMENT),
    FOREIGN KEY (REF_EMPLACEMENT_CIBLE) REFERENCES EMPLACEMENTS(REF_EMPLACEMENT)
);

CREATE TABLE IF NOT EXISTS ANOMALIES_SUPERVISEUR (
    ID_ANOMALIE INTEGER PRIMARY KEY AUTOINCREMENT,
    DATE_ALERTE DATETIME DEFAULT CURRENT_TIMESTAMP,
    TYPE_ANOMALIE VARCHAR(50) NOT NULL,
    CODE_BARRE VARCHAR(50) NOT NULL,
    REF_EMPLACEMENT VARCHAR(50),
    QTE_ATTENDUE INT NOT NULL,
    QTE_CONSTATEE INT NOT NULL,
    STATUT VARCHAR(50) NOT NULL,
    ID_SIGNALEUR INTEGER NOT NULL,
    ID_SUPERVISEUR INTEGER,
    FOREIGN KEY (CODE_BARRE) REFERENCES ARTICLES_SKU(CODE_BARRE),
    FOREIGN KEY (REF_EMPLACEMENT) REFERENCES EMPLACEMENTS(REF_EMPLACEMENT),
    FOREIGN KEY (ID_SIGNALEUR) REFERENCES UTILISATEURS(ID_EMPLOYÉ),
    FOREIGN KEY (ID_SUPERVISEUR) REFERENCES UTILISATEURS(ID_EMPLOYÉ)
);

-- Triggers Anti-Mélange : Empêchent de stocker un code-barres différent dans un casier déjà occupé
CREATE TRIGGER IF NOT EXISTS ANTI_MELANGE_STOCK_INSERT
BEFORE INSERT ON STOCK_EMPLACEMENTS
FOR EACH ROW 
BEGIN
    SELECT RAISE(ABORT, 'Erreur : Règle Anti-Mélange violée ! Ce casier contient déjà une autre référence ou pointure.')
    WHERE EXISTS (
        SELECT 1 FROM STOCK_EMPLACEMENTS
        WHERE REF_EMPLACEMENT = NEW.REF_EMPLACEMENT 
          AND CODE_BARRE != NEW.CODE_BARRE
          AND QUANTITE > 0
    );
END;

CREATE TRIGGER IF NOT EXISTS ANTI_MELANGE_STOCK_UPDATE
BEFORE UPDATE ON STOCK_EMPLACEMENTS
FOR EACH ROW 
BEGIN
    SELECT RAISE(ABORT, 'Erreur : Règle Anti-Mélange violée lors de la modification du casier !')
    WHERE EXISTS (
        SELECT 1 FROM STOCK_EMPLACEMENTS
        WHERE REF_EMPLACEMENT = NEW.REF_EMPLACEMENT 
          AND CODE_BARRE != NEW.CODE_BARRE
          AND ID_STOCK != NEW.ID_STOCK
          AND QUANTITE > 0
    );
END;