CREATE TABLE IF NOT EXISTS MODELES (
    ID_MODELE INT PRIMARY KEY AUTO_INCREMENT,
    NOM_MODELE VARCHAR(255) NOT NULL,
    MARQUE VARCHAR(255),
    COULEUR VARCHAR(100),
    PRIX_UNITAIRE DECIMAL(10, 2) NOT NULL
)

CREATE TABLE IF NOT EXISTS ARTICLES_SKU ( 
    CODE_BARRE VARCHAR(50) PRIMARY KEY,
    ID_MODELE INT,
    TAILLE VARCHAR(50),
    STOCK_PHYSIQUE INT DEFAULT 0,
    STOCK_RESERVE INT DEFAULT 0,
    FOREIGN KEY (ID_MODELE) REFERENCES MODELES(ID_MODELE)
);

CREATE TABLE IF NOT EXISTS EMPLACEMENTS (
    REF_EMPLACEMENT VARCHAR(50) PRIMARY KEY,
    CAPACITE_MAX INT NOT NULL CHECK (CAPACITE_MAX >0),
    ARTICLES_PRESENTS INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS STOCK_EMPLACEMENTS (
    ID_STOCK INT PRIMARY KEY AUTO_INCREMENT,
    CODE_BARRE VARCHAR(50),
    REF_EMPLACEMENT VARCHAR(50),
    QUANTITE INT CHECK (QUANTITE >= 0),
    FOREIGN KEY (CODE_BARRE) REFERENCES ARTICLES_SKU(CODE_BARRE),
    FOREIGN KEY (REF_EMPLACEMENT) REFERENCES EMPLACEMENTS(REF_EMPLACEMENT)
);

CREATE TABLE IF NOT EXISTS UTILISATEURS (
    ID_EMPLOYÉ INT PRIMARY KEY AUTO_INCREMENT,
    IDENTIFIANT VARCHAR(255) NOT NULL UNIQUE,
    MOT_DE_PASSE VARCHAR(255) NOT NULL,
    NOM_COMPLET VARCHAR(255) NOT NULL
);
